# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
    #branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # For gcloud https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions
    permissions:
      contents: 'read'
      id-token: 'write'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: build
        run: |
          mvn package

      # https://github.com/google-github-actions/auth#setting-up-workload-identity-federation
      - name: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: 'projects/445858285591/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'github-ci@world-340022.iam.gserviceaccount.com'

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: 'world-health'
          runtime: 'java11'
          region: europe-west3
          max_instances: 1
          memory_mb: 128
          env_vars: HEALTH=OK

      # Example of using the output
      - name: 'url'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
